# Generated by Django 2.2.6 on 2020-04-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='availability_date',
            field=models.DateField(null=True, verbose_name='available date'),
        ),
    ]
